### ISSUE TITLE
Changes for Univention Corporate Server

### ISSUE THREAD

**Issue by philippludwig** [splitbrain/dokuwiki-plugin-pureldap#8]
This may or may not be of interest to someone.

To have this plugin work with the Univention corporate server (UCS), I had to make two small changes:

* In `ADClient.php`, I changed the function `qualifiedUser` to just return `$user`. The reason is that we don’t need (or should not add) the suffix for LDAP binds with UCS; that is considered "invalid".
* In `Client.php` in the function `authenticate`, I changed the call to `$this->ldap->bind` in such a way that instead of just the `$user` variable being passed, it is `"uid=" . $user . "," . $this->config['base_dn']`. The reason is that for a valid bind, we need to request it from UCS (which runs slapd) in the form of `uid=username,cn=users,dc=domain,dc=domainsuffix`. Otherwise the bind is not valid.

**Comment by splitbrain** [comment]
Despite the name, the plugin currently only supports Microsoft Active Directory. Adding generic LDAP support is a goal that is currently looking for funding.
